--- # off-shore location specifications

path:
    platform:
        local: 
            d22: 
                path_template: ["/lustre/storeB/immutable/archive/projects/\
                                metproduction/DNMI_OFFSHORE/platform/d22/%Y/", 
                                "/vol/gorgon/offshore/platform/d22/"]
                file_template: '%Y%m%d.d22'
                strsub: ['platform'] # part of string to be substituted
            nc: 
                path_template: ["/home/patrikb/tmp_station/%Y/%m/",
                                "/lustre/storeB/project/fou/om/\
                                 waveverification/obs/stations/%Y/%m/"]
                file_template: 'varalias_10min_platform_sensor_%Y%m.nc'
                strsub: ['varalias','platform','sensor']
        remote:
        misc:
            vardef: # stdname: abbreviation
                #sea_surface_wave_significant_height: Hs_10min
platform:
    draugen:
        sensor:
            MKIIIradar_1: 0 # python indexing
        manufacturer:
            MKIIIradar_1: Miros
        coords:
            lat: 64.35
            lon: 7.78
        operator: OKEA
        twin: 1
    ekofiskL:
        sensor:
            SAABWaveRadar: 2
        manufacturer:
            SAABWaveRadar: Rosemount
        coords:
            lat: 56.54
            lon: 3.21
        operator: ConocoPhillips_Skandinavia
    grane:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 59.17
            lon: 2.48
        operator: Equinor_Energy
    oseberg:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 60.5
            lon: 2.8
        operator: NA
    osebergc:
        sensor:
            NA_1: 0 # python indexing
        manufacturer:
            NA_1: NA
        coords:
            lat: 60.64
            lon: 2.78
        operator: NA
    gullfaksc:
        sensor: 
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 56.28
            lon: 3.39
        operator: Equinor_Energy
        twin: 1
    heimdal:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 59.57
            lon: 2.23
        operator: Equinor_Energy
        twin: 1
    kvitebjorn:
        sensor:
            NA_1: 0
        manufacturer:
            NA_1: NA
        coords:
            lat: 61.08
            lon: 2.49
        operator: Equinor_Energy
        twin: 1
    norne:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 66.02
            lon: 8.08
        operator: Equinor_Energy
        twin: 1
    snorrea:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 61.45
            lon: 2.15
        operator: Equinor_Energy
    snorreb:
        sensor:
            NA_1: 0 # python indexing
        manufacturer:
            NA_1: NA
        coords:
            lat: 61.52
            lon: 2.21
        operator: Equinor_Energy
    sleipner:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 58.37
            lon: 1.91
        operator: Equinor_Energy
        twin: 1
    stafjorda: # established typo should be stafjord
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 61.25
            lon: 1.85
        operator: Equinor_Energy
    trolla:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 60.64
            lon: 3.72
        operator: Equinor_Energy
        twin: 1
    visund:
        sensor:
            MKIIIradar: 0 # python indexing
        manufacturer:
            MKIIIradar: Miros
        coords:
            lat: 61.37
            lon: 2.46
        operator: Equinor_Energy
